apiVersion: v1
kind: ConfigMap
metadata:
  name: bezkoder-config
data:
  MYSQLDB_USER: root
  MYSQLDB_DATABASE: bezkoder_db
  MYSQLDB_LOCAL_PORT: "3307"
  MYSQLDB_DOCKER_PORT: "3306"
  SPRING_LOCAL_PORT: "6868"
  SPRING_DOCKER_PORT: "8080"
