apiVersion: apps/v1
kind: Deployment
metadata:
  name: bezkoder-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bezkoder-app
  template:
    metadata:
      labels:
        app: bezkoder-app
    spec:
      containers:
        - name: bezkoder-app
          image: spring-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: MYSQLDB_USER
              valueFrom:
                configMapKeyRef:
                  name: bezkoder-config
                  key: MYSQLDB_USER
            - name: MYSQLDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: bezkoder-config
                  key: MYSQLDB_DATABASE
            - name: MYSQLDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bezkoder-secret
                  key: MYSQLDB_ROOT_PASSWORD
            - name: MYSQLDB_DOCKER_PORT
              valueFrom:
                configMapKeyRef:
                  name: bezkoder-config
                  key: MYSQLDB_DOCKER_PORT
            - name: SPRING_APPLICATION_JSON
              valueFrom:
                configMapKeyRef:
                  name: bezkoder-config
                  key: SPRING_APPLICATION_JSON
      restartPolicy: Always
